#!/usr/bin/python

import sys
import os

def main():
    from seleniumwebtests.__main__ import main as seleniumwebtests_main
    sys.path.append(os.getcwd())
    return seleniumwebtests_main()

if __name__ == "__main__":
    sys.exit(main())
